import { Metadata } from "next";
import { CartUsers } from "@/components/cart";

export const metadata: Metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

const Cart = () => {
  return <>{/* <CartUsers /> */}</>;
};

export default Cart;
