import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <div>
      <h2>This page contains information about us</h2>
    </div>
  );
};

export default AboutUs;
