import "../styles/globals.css";
import { Footer, Nav } from "@/components/sharedLayoutsrafce";
import { CartProvider, HomeProvider } from "@/contextrafce";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeProvider>
          <CartProvider>
            <Nav />
            {children}
            <Footer />
          </CartProvider>
        </HomeProvider>
      </body>
    </html>
  );
}
