export const electronics = [
  {
    id: 1,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-12.jpeg",
    type: "Modern Poster",
    price: "30.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    details: {
      name: "Modern Poster",
      rating: 1,
      reviews: "(100 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecQ0fMd8T0Vk211E",
      brand: "Liddy",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 2,
    category: "Bedroom",
    image: "https://www.course-api.com/images/store/product-4.jpeg",
    type: "Armchair",
    price: "125.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Marcos",
    details: {
      name: "Armchair",
      rating: 1,
      reviews: "(33 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Recd1jIVIEChmiwhe",
      brand: "Marcos",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 3,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-16.jpeg",
    type: "Suede Armchair",
    price: "159.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Suede Armchair",
      rating: 1,
      reviews: "(10 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecroK1VD8qVdMP5H",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 4,
    category: "Bedroom",
    image: "https://www.course-api.com/images/store/product-9.jpeg",
    type: "Leather Chair",
    price: "200.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Leather Chair",
      rating: 1,
      reviews: "(17 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecoW8ecgjtKx2Sj2",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },
  {
    id: 5,
    category: "Bedroom",
    image: "https://www.course-api.com/images/store/product-6.jpeg",
    type: "Emperor Bed",
    price: "239.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Emperor Bed",
      rating: 1,
      reviews: "(60 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Rec1Ntk7siEEW9ha1",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 6,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-1.jpeg",
    type: "Accent Chair",
    price: "259.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Marcos",
    details: {
      name: "Accent Chair",
      rating: 1,
      reviews: "(25 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecZkNf2kwmdBcqd0",
      brand: "Marcos",
    },

    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 7,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-13.jpeg",
    type: "Shelf",
    price: "309.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Shelf",
      rating: 1,
      reviews: "(38 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Rec7CjDWKRgNQtrKe",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 8,
    category: "Kids",
    image: "https://www.course-api.com/images/store/product-11.jpeg",
    type: "Modern Bookshelf",
    price: "319.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Modern Bookshelf",
      rating: 1,
      reviews: "(27 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecoAJYUCuEKxcPSr",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 9,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-8.jpeg",
    type: "High-Back Bench",
    price: "399.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "High-Back Bench",
      rating: 1,
      reviews: "(19 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Recrfxv3EwpvJwvjq",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 10,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-21.jpeg",
    type: "Wooden Desk",
    price: "400.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Wooden Desk",
      rating: 1,
      reviews: "(14 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Recm7wC8TBVdU9oEL",
      brand: "Ikea",
    },

    isInCart: false,
    isInStock: true,
    counter: 1,
  },
];

export const fashion = [
  {
    id: 1,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-5.jpeg",
    type: "Entertainment Center",
    price: "599.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Entertainment Center",
      rating: 1,
      reviews: "(100 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecNZ0koOqEmilmoz",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 2,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-7.jpeg",
    type: "Utopia Sofa",
    price: "799.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    details: {
      name: "Utopia Sofa",
      rating: 1,
      reviews: "(10 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Rec7JInsuCEHgmaGe",
      brand: "Liddy",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 3,
    category: "Dining Room",
    image: "https://www.course-api.com/images/store/product-17.jpeg",
    type: "Dining Table",
    price: "429.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Dining Table",
      rating: 1,
      reviews: "(200 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecotY5Nh00DQFdkm",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 4,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-10.jpeg",
    type: "Leather Sofa",
    price: "999.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Leather Sofa",
      rating: 1,
      reviews: "(44 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecEOA6qtDag1hRbU",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 5,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-2.jpeg",
    type: "Albany Sectional",
    price: "1,099.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    details: {
      name: "Albany Sectional",
      rating: 1,
      reviews: "(123 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "Out Of Stock",
      sku: "RecEHmzvupvT8ZONH",
      brand: "Liddy",
    },
    isInCart: false,
    isInStock: false,
    counter: 1,
  },

  {
    id: 6,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-14.jpeg",
    type: "Simple Chair",
    price: "1,099.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    details: {
      name: "Simple Chair",
      rating: 1,
      reviews: "(400 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "Out Of Stock",
      sku: "RecF0KpwlkF7e8kXO",
      brand: "Liddy",
    },
    isInCart: false,
    isInStock: false,
    counter: 1,
  },

  {
    id: 7,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-18.jpeg",
    type: "Vase Table",
    price: "1,209.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Marcos",
    details: {
      name: "Vase Table",
      rating: 1,
      reviews: "(12 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Rec3jeKnhInKHJuz2",
      brand: "Marcos",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 8,
    category: "Living Room",
    image: "https://www.course-api.com/images/store/product-15.jpeg",
    type: "Sofa Set",
    price: "1,299.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Marcos",
    details: {
      name: "Sofa Set",
      rating: 1,
      reviews: "(45 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Recs5BSVU3qQrOj4E",
      brand: "Marcos",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 9,
    category: "Office",
    image: "https://www.course-api.com/images/store/product-20.jpeg",
    type: "Wooden Desk",
    price: "1,509.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Wooden Desk",
      rating: 1,
      reviews: "(300 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RecJIjREF3dlFi3sR",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 10,
    category: "Kitchen",
    image: "https://www.course-api.com/images/store/product-22.jpeg",
    type: "Wooden Table",
    price: "2,349.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Caressa",
    details: {
      name: "Wooden Table",
      rating: 1,
      reviews: "(35 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "RectfNsySwAJeWDN2",
      brand: "Caressa",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 11,
    category: "Bedroom",
    image: "https://www.course-api.com/images/store/product-19.jpeg",
    type: "Wooden Bed",
    price: "2,500.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Ikea",
    details: {
      name: "Wooden Bed",
      rating: 1,
      reviews: "(123 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Recv2ohxljlK2FZO7",
      brand: "Ikea",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },

  {
    id: 12,
    category: "Kitchen",
    image: "https://www.course-api.com/images/store/product-3.jpeg",
    type: "Albany Table",
    price: "3,099.99",
    reviews: "(100 customer reviews)",
    content:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    details: {
      name: "Albany Table",
      rating: 1,
      reviews: "(34 customer reviews)",
      content:
        "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
      available: "In Stock",
      sku: "Rec5NBwZ5zCD9nfF0",
      brand: "Liddy",
    },
    isInCart: false,
    isInStock: true,
    counter: 1,
  },
];
